### ISSUE TITLE
cannot pull ?

### ISSUE THREAD

**Issue by robov** [RevianLabs/MediaWiki-VisualEditor-Docker#1]
pull access denied for mediawiki-parsoid, repository does not exist or may require 'docker login'

**Comment by SCBbestof** [comment]
Hi @robov,

I have tried to replicate it on different computers and on a CentOS VM. Everything worked fine.
It should work for you as well, since the docker image is public.

Worst-case, you could build it yourself by cloning this repository, opening a terminal withing the cloned directory and running `docker` build -t revianlabs/mediawiki-ve-bundle .`

Please let me know if this was helpful.

Thanks,
Bogdan

**Comment by Grawl** [comment]
```Step 19/22 : RUN rm config.example.yaml && npm install
 ---> Running in 882c0542c1c9
/bin/sh: 1: npm: not found
The command '/bin/sh -c rm config.example.yaml && npm install' returned a non-zero code: 127
```

**Comment by SCBbestof** [comment]
Hi @Grawl,

Thank you for reporting the issue.
It was fixed with a Node upgrade and documented in #2.

**Comment by SCBbestof** [comment]
Closed this due to inactivity. If the issue persists, please comment so I can reopen it. :)

**Comment by Grawl** [comment]
👍

**Comment by rec** [comment]
I just saw exactly this issue on both MacOS and Ubuntu 18.04.

I'm going to try your workaround now (thanks!) - let me know how I can help you debug this!

Transcript follows.  The docker-compose.yml was taken directly from here, unchanged.

----

   $ docker-compose up -d
    Creating network "test_default" with the default driver
    Creating volume "test_mariadb_data" with local driver
    Creating volume "test_mediawiki_data" with local driver
    Creating volume "test_parsoid_data" with local driver
    Pulling mediawiki (mediawiki-parsoid:)...
    ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

    Continue with the new image? [yN]y
    Pulling mediawiki (mediawiki-parsoid:)...
    ERROR: pull access denied for mediawiki-parsoid, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by rec** [comment]
https://hub.docker.com/_/mediawiki-parsoid gives me an error.  

My best guess is that the second half of this claim is false: "It should work for you as well, since the docker image is public."

:-)

**Comment by rec** [comment]
If anyone needs a workaround for the moment, the image tomswirly/mediawiki-parsoid is a publicly readable copy of this image!

I'll take it down once this problem is resolved.  :-)

**Comment by SCBbestof** [comment]
> If anyone needs a workaround for the moment, the image tomswirly/mediawiki-parsoid is a publicly readable copy of this image!
> 
> I'll take it down once this problem is resolved. :-)

Auch... didn't saw that. I guess it got removed for some reason. :(
I will update the repo.

**Comment by SCBbestof** [comment]
It seems like Mediawiki is going to integrate Parsoid directly into the App. Therefore, there is no Parsoid image anymore. Seems weird to just remove it, but I'll switch to the one recommended by @rec for now and I'll rework this once Parsoid is stable within Mediawiki.

Thank you @rec for the research. Highly appreciated!

**Comment by SCBbestof** [comment]
Fixed by #3

**Comment by rec** [comment]
Thanks for doing this!  

As a note, Mediawiki has been working on getting rid of Parsoid as a separate service since 2012, and their plan is to have it done by June of 2020.  

Having worked in the field of software development for decades, I can assure you that this date is completely certain, and that they will surely be done in five months.  NOT.  :-D

**Comment by SCBbestof** [comment]
> Thanks for doing this!
> 
> As a note, Mediawiki has been working on getting rid of Parsoid as a separate service since 2012, and their plan is to have it done by June of 2020.
> 
> Having worked in the field of software development for decades, I can assure you that this date is completely certain, and that they will surely be done in five months. NOT. :-D

No problem :)

I read that on their documentation. It seems like they planned it for early-mid 2019, then postponed it to december 2019, and now it's expected to drop in June 😁
Fortunately, the image that is used now shouldn't be broken by the change, since it version-locked Parsoid and Mediawiki.
