### ISSUE TITLE
Error when using the provided docker-compose or with the volume

### ISSUE THREAD

**Issue by IXEguy** [RevianLabs/MediaWiki-VisualEditor-Docker#4]
I took the provided docker-compose and removed the mariadb lines (was gonna use my own instance) and tried to run it & get the following error for the image that it is supposed to use:
```
Pulling mediawiki (mediawiki-parsoid:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]
ERROR: pull access denied for mediawiki-parsoid, repository does not exist or may require 'docker login'
```

So, I tried with the provided one-liner while inside a directory in my home dir & got this in the container logs when I try to access the container:
```
[Thu Jun 18 23:12:02.011214 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.1.33 configured -- resuming normal operations


[Thu Jun 18 23:12:02.011270 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'


[Thu Jun 18 23:12:17.010756 2020] [autoindex:error] [pid 24] [client 192.168.69.420:65530] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive


192.168.69.420 - - [18/Jun/2020:23:12:17 +0000] "GET / HTTP/1.1" 403 489 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"


192.168.69.420 - - [18/Jun/2020:23:12:17 +0000] "GET /favicon.ico HTTP/1.1" 404 485 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
```
Which makes sense since the directory it is pointed at is still empty at this point.

If I create it without the volume, it seems to come up correctly and ask me to proceed with setup.

Any suggestions?

**Comment by danielshawellis** [comment]
I was able to resolve this by using the updated MediaWiki image in the docker-compose.yml file. The README is outdated.

You should replace this line in the README:
`image: 'mediawiki-parsoid'`

with this line from the updated compose file:
`image: 'revianlabs/mediawiki-ve-bundle'`

**Comment by SCBbestof** [comment]
> I was able to resolve this by using the updated MediaWiki image in the docker-compose.yml file. The README is outdated.
> 
> You should replace this line in the README:
> `image: 'mediawiki-parsoid'`
> 
> with this line from the updated compose file:
> `image: 'revianlabs/mediawiki-ve-bundle'`

Good catch. Readme updated.
